name: build and deploy urlshortner
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    name: build and deploy urlshortner
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: urlshortnerdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Wait for MySQL to be healthy
        run: |
            echo "Waiting for MySQL..."
            while ! mysqladmin ping -h"127.0.0.1" --silent; do
              sleep 1
            done
      - name: Set up MySQL client
        run: sudo apt-get install -y mysql-client

      - name: Run tests with Maven
        env:
            SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/urlshortnerdb
            SPRING_DATASOURCE_USERNAME: testuser
            SPRING_DATASOURCE_PASSWORD: testpass
        run: mvn clean install

      - name: build the app
        run: |
          mvn clean
          mvn install
      - name: build the docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/urlshortner:latest

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: push the docker image to docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/rest-api:latest